{
 "title": "Firewall",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "description": "An administratively-assigned name for this managed node. By convention, this is the node's fully-qualified domain name. If the name is unknown, the value is the zero-length string",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "hostname" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "A textual description of the entity. This value should include the full name and version identification of the system's hardware type, software operating-system, and networking software",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "OS Version",
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"os_version\") FROM \"Afranet-R5_interfaces\" WHERE $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "os_version" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "The time (in hundredths of a second) since the network management portion of the system was last re-initialized",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Uptime",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"uptime\") FROM \"snmp\" WHERE (\"host\" = 'telegraf') AND $timeFilter GROUP BY time(1m), \"hostname\" fill(null)",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "High-availability mode",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HA System Mode",
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"os_version\") FROM \"Afranet-R5_interfaces\" WHERE $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "ha_mode" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "description": "Configuration of an automatic configuration synchronization",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "HA Auto Sync",
     "measurement": "YOUR-NAME",
     "query": "SELECT last(\"os_version\") FROM \"Afranet-R5_interfaces\" WHERE $timeFilter GROUP BY \"hostname\"",
     "select": [
      [
       { "params": [ "ha_auto_sync" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "Current CPU usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Current memory utilization",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "usage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Rate (IN)",
   "type": "timeseries",
   "description": "The total number of octets received and transmitted on the interface, including framing characters. Discontinuities in the value of this counter can occur at re-initialization of the management system, and at other times as indicated by the value of ifCounterDiscontinuityTime",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  NON_NEGATIVE_DERIVATIVE(last(\"ifInOctets\"), 1s) *8 FROM \"YOUR-NAME\" WHERE (\"ifOperStatus\"=1) AND $timeFilter GROUP BY time($__interval), \"ifName\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Data Rate (OUT)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "$tag_ifName",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  NON_NEGATIVE_DERIVATIVE(last(\"ifOutOctets\"), 1s) *8 FROM \"YOUR-NAME\" WHERE (\"ifOperStatus\"=1) AND $timeFilter GROUP BY time($__interval), \"ifName\" fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Port Summary",
   "type": "table",
   "description": "An entry containing management information applicable to a particular interface",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ifIndex" ], "type": "tag" },
      { "params": [ "ifName" ], "type": "tag" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "ifAlias" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifHighSpeed" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " *1000000" ], "type": "math" }
      ],
      [
       { "params": [ "ifInErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifOperStatus" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifOutErrors" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ifType" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "ifIndex" ], "type": "tag" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "ip" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "net_mask" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HA Stats",
   "type": "timeseries",
   "description": "Statistics for a particular HA cluster's unit",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "targets": [
    {
     "alias": "$tag_ha_stats_index",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ha_stats_index" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "ha_stats_sync_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "ha_stats_index" ], "type": "tag" }
     ],
     "measurement": "YOUR-NAME",
     "select": [
      [
       { "params": [ "ha_stats_cpu_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ha_stats_memory_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ha_stats_net_usage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ha_stats_ses_count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ha_stats_hostname" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ],
      [
       { "params": [ "ha_stats_sync_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}